apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "production-rag.labels" . | nindent 4 }}
type: Opaque
stringData:
  groq-api-key: {{ .Values.secrets.groqApiKey | quote }}
  neo4j-password: {{ .Values.secrets.neo4jPassword | quote }}
  minio-root-user: {{ .Values.secrets.minioRootUser | quote }}
  minio-root-password: {{ .Values.secrets.minioRootPassword | quote }}
